### ISSUE TITLE
Are TenantResolver.java, TenantJWSKeySelector.java, TenantJwtIssuerValidator.java required?

### ISSUE THREAD

**Issue by manuongithub** [jzheaux/springone2019#4]
Hi,

Are TenantJWSKeySelector.java, TenantJwtIssuerValidator.java in Message still required and if yes then can you please explain how they are used.

Thanks,
Manu

**Comment by delopst** [comment]
Hi, 

I think that: 

`JwtDecoders.fromIssuerLocation(issuerUrl)` retrieves configuration with issuerUrl (configuration includes jwsSetUrl) and than creates `NimbusJwtDecoder`.

The next two examples are copied from the source code.

```  
private static JwtDecoder withProviderConfiguration(Map<String, Object> configuration, String issuer) {
        JwtDecoderProviderConfigurationUtils.validateIssuer(configuration, issuer);
        OAuth2TokenValidator<Jwt> jwtValidator = JwtValidators.createDefaultWithIssuer(issuer);
        NimbusJwtDecoder jwtDecoder =    NimbusJwtDecoder.withJwkSetUri(configuration.get("jwks_uri").toString()).build();
        jwtDecoder.setJwtValidator(jwtValidator);
        return jwtDecoder;
    }
```

```
 public NimbusJwtDecoder build() {
            return new NimbusJwtDecoder(this.processor());
 }

 WTProcessor<SecurityContext> processor() {
            JWSKeySelector<SecurityContext> jwsKeySelector = 
                                   new    SingleKeyJWSKeySelector(this.jwsAlgorithm, this.secretKey);
            DefaultJWTProcessor<SecurityContext> jwtProcessor = new DefaultJWTProcessor();
            jwtProcessor.setJWSKeySelector(jwsKeySelector);
            jwtProcessor.setJWTClaimsSetVerifier((claims, context) -> {});
            return jwtProcessor;
}
```

If you would like to use TenantJWSKeySelector and TenantJwtIssuerValidator, you could use the following example, but I think that the current solution is cleaner :).

```
@Bean
public JwtDecoder jwtDecoder(
     TenantJWSKeySelector tenantJWSKeySelector,
     TenantJwtIssuerValidator tenantJwtIssuerValidator ) {

      DefaultJWTProcessor<SecurityContext> jwtProcessor =
            new DefaultJWTProcessor<>();
      jwtProcessor.setJWSKeySelector(tenantJWSKeySelector);

      NimbusJwtDecoder decoder = new NimbusJwtDecoder(jwtProcessor);
      decoder.setJwtValidator(tenantJwtIssuerValidator);
      return decoder;
}
```

Regards, Primož

**Comment by jzheaux** [comment]
Spring Security 5.3 shipped with [`JwtIssuerAuthenticationManagerResolver`](https://docs.spring.io/spring-security/site/docs/5.3.3.RELEASE/reference/html5/#oauth2resourceserver-multitenancy), which does remove the need for these classes.

One small tradeoff is that this resolver parses the JWT in order to extract the issuer claim, and then the corresponding `JwtDecoder` will parse the JWT again in order to verify it. For most workloads, this additional parse will have a negligible effect on performance.

In circumstances where that optimization is important, the reference guide contains [some additional details](https://docs.spring.io/spring-security/site/docs/5.3.3.RELEASE/reference/html5/#parsing-the-claim-only-once) that relate to the continued use of the classes you mentioned here.
